assert_lefthook_installed: true
pre-commit:
  commands:
    check:
      run: npm run check
      stage_fixed: true
    format:
      run: npm run format
      stage_fixed: true
    lint:
      run: npm run lint
      stage_fixed: true
